<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-5EVK54D" failures="1" tests="1" name="Default test(failed)(failed)" time="0.125" errors="0" timestamp="2022-08-01T08:20:57 IST">
  <testcase classname="testngdiscussion.ExecuteFailedTestCase" name="home" time="0.021">
    <failure type="java.lang.AssertionError" message="Failing test case deliberately">
      <![CDATA[java.lang.AssertionError: Failing test case deliberately
at testngdiscussion.ExecuteFailedTestCase.home(ExecuteFailedTestCase.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- home -->
  <testcase classname="testngdiscussion.ExecuteFailedTestCase" name="dashBoard" time="0.0">
    <ignored/>
  </testcase> <!-- dashBoard -->
  <testcase classname="testngdiscussion.ExecuteFailedTestCase" name="logout" time="0.0">
    <ignored/>
  </testcase> <!-- logout -->
  <testcase classname="testngdiscussion.ExecuteFailedTestCase" name="login" time="0.0">
    <ignored/>
  </testcase> <!-- login -->
  <testcase classname="testngdiscussion.ExecuteFailedTestCase" name="profile" time="0.0">
    <ignored/>
  </testcase> <!-- profile -->
</testsuite> <!-- Default test(failed)(failed) -->
